name: CI - Nutria API SQL

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (sem testes unitários)
        run: mvn -B package -Dmaven.test.skip=true
        working-directory: ./ms-nutria-postgresql

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Verificação de formatação e estilo
        run: mvn -B spotless:check
        working-directory: ./ms-nutria-postgresql